sudo: false
dist: trusty
language: node_js
jobs:
  allow_failures:
    - env: WEBPACK_VERSION=canary
  include:
    - node_js: 6
      env: WEBPACK_VERSION=latest JOB_PART=lint
      script: npm run $JOB_PART
    - node_js: 6
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run $JOB_PART
    - node_js: 8
      env: WEBPACK_VERSION=latest JOB_PART=coverage
      script: npm run $JOB_PART
    - node_js: 10
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run $JOB_PART
      after_success: 'bash <(curl -s https://codecov.io/bash)'
    - node_js: 11
      env: WEBPACK_VERSION=latest JOB_PART=test
      script: npm run $JOB_PART
before_install:
  - 'if [[ `npm -v | cut -d . -f 1` -lt 5 ]]; then npm i -g npm@^5.0.0; fi'
  - nvm --version
  - node --version
  - npm --version
before_script:
  - |-
    if [ "$WEBPACK_VERSION" ]; then
      npm i --no-save webpack@$WEBPACK_VERSION
    fi
script:
  - 'npm run $JOB_PART'
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'